#!/bin/bash
###############################################################################
#
# This script belongs to the FLOW3 framework.
#
# It is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This script is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-
# TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with the script.
# If not, see http://www.gnu.org/licenses/lgpl.html
#
# The TYPO3 project - inspiring people to share!
#
###############################################################################

##
#
# @package FLOW3
# @author Tobias Liebig <mail_typo3@etobi.de>
# @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License, version 3 or later
#

# Configuration

# Absolute path to php executable if not set yet
PHP=${PHP:="php"};

FLOW3_CONTEXT=${FLOW3_CONTEXT:="Development"};

# Getting root path of FLOW3 if not set yet
CURRENT_PATH="$(pwd)"
cd "$(dirname $0)"
FLOW3_ROOTPATH=${FLOW3_ROOTPATH:="$(pwd)"};
cd "${CURRENT_PATH}"

FLOW3_WEBPATH="$FLOW3_ROOTPATH/Web";

FLOW3_DEBUG=${FLOW3_DEBUG:=false}

FLOW3_SHELLCONFIGFILE="${FLOW3_ROOTPATH}/Configuration/flow3.sh"
if [ -f "${FLOW3_SHELLCONFIGFILE}" ]; then
    . "${FLOW3_SHELLCONFIGFILE}"
fi

BOOTSTRAP='Packages/Framework/FLOW3/Scripts/FLOW3.php'
PACKAGE=''
SUBPACKAGES=''
CONTROLLER=''
ACTION=''
ARGUMENTS=''

printUsage () {
	echo 'FLOW3 Command Line Interface'
	echo ''
	echo 'usage: flow3 <options> <command>'
	echo ''
	echo 'Options:'
	echo ''
	echo '  -h, --help        - print this message'
	echo '  -p, --production  - execute in production context'
	echo '  -s, --setup       - execute in setup context'
	echo ''
	echo 'Environment variables used (optional):'
	echo ''
	echo '  FLOW3_CONTEXT     - defines the context to use'
	echo '  FLOW3_ROOTPATH    - defines the FLOW3 root path'
	echo '  FLOW3_WEBPATH     - defines the FLOW3 web path'
	echo '  FLOW3_DEBUG       - enable debug mode with "true"'
	echo '  PHP               - the PHP CLI binary to use'
	echo ''
	echo 'Available commands:'
	echo ''
	echo '  package list available           - list available packages'
	echo '  package list active              - list active packages'
	echo '  package create <package-key>     - create a new package'
	echo '  package activate <package-key>   - activate a package'
	echo '  package deactivate <package-key> - deactivate a package'
	echo '  package delete <package-key>     - delete a package'
	echo ''
	echo '  cache flush                      - flush all caches'
	echo ''
	echo '  testing <package-key> <output-directory> [<testcase> [<coverage-directory>]] '
	echo '                                   - run unit tests'
	echo '                                     <package-key> Package to test (mandatory)'
	echo '                                     <output-directory> path to write the logfile.xml (mandatory)'
	echo '                                     <testcase> only run this testcase (optional)'
	echo '                                     <coverage-directory> path to write the clover.xml (optional)'
	echo ''
	echo '  kickstart package <package-key>'
	echo '                                   - kickstart a new package, including a standard controller'
	echo '                                     <package-key> Package for the controller (mandatory)'
	echo ''
	echo '  kickstart controller <package-key> [<controller-name>]'
	echo '                                   - generate a controller'
	echo '                                     <package-key> Package for the controller (mandatory)'
	echo '                                     <controller-name> Name of the controller, can also be a comma separated list of multiple controller names (optional)'
	echo ''
	echo '  kickstart model <package-key> <model-name>'
	echo '                                   - generate a model'
	echo '                                     <package-key> Package for the model (mandatory)'
	echo '                                     <model-name> Name of the model (mandatory)'
	echo ''
	echo '  kickstart repository <package-key> [<model-name>]'
	echo '                                   - generate a repository'
	echo '                                     <package-key> Package for the controller (mandatory)'
	echo '                                     <model-name> Name of the model the repository is for (mandatory)'
	echo ''
	echo '  migrate testnamespaces'
	echo '                                   - migrates to the new test namespaces for unit tests and functional tests as required since 1.0.0 alpha 13'
	echo ''
	exit 1
}

# check minimum argument count
if [ $# -lt 2 ]; then
	printUsage
fi

# parse argument list
while [ $# -ge 1 ]; do
	case $1 in
	help|--help|-h)
		printUsage
		;;

	--production|-p)
		FLOW3_CONTEXT='Production'
		;;

	--setup|-s)
		FLOW3_CONTEXT='Setup'
		;;

	package)
		PACKAGE='FLOW3'
		SUBPACKAGES='Package'
		CONTROLLER='PackageManager'
		shift
		case $1 in
		create|activate|deactivate|delete)
			if [ $# -ne 2 ]; then
				echo 'Please specify a package-key'
				echo
				printUsage
			else
				ACTION=$1
				shift
				ARGUMENTS="--package-key=$1"
			fi
			;;
		list)
			shift
			ACTION="list$1"
		esac
		;;

	testing)
		PACKAGE='Testing'
		CONTROLLER='Cli'
		ACTION='run'
		shift
		if [ $# -lt 2 ]; then
			echo 'Please specify a package-key and output-directory'
			echo
			printUsage
		else
			ARGUMENTS="--package-key=$1"
			shift
			ARGUMENTS="$ARGUMENTS --output-directory=$1"

			if [ $# -gt 1 ]; then
				shift
				ARGUMENTS="$ARGUMENTS --testcase=$1"
			fi
			if [ $# -gt 1 ]; then
				shift
				ARGUMENTS="$ARGUMENTS --coverage-directory=$1"
			fi
		fi
		;;

	cache)
		shift
		if [ "$1" = 'flush' ]; then
			PACKAGE='FLOW3'
			SUBPACKAGES='Cache'
			CONTROLLER='CacheManager'
			ACTION='flush'
		fi
		;;

	migrate)
		shift
		if [ "$1" = 'testnamespaces' ]; then
			PACKAGE='Foo'
			CONTROLLER='Bar'
			ACTION='migrate'
			BOOTSTRAP='Packages/Framework/FLOW3/Scripts/migratetestnamespaces.php'
		fi
		;;

	kickstart)
		PACKAGE='Kickstart'
		CONTROLLER='Kickstart'
		shift
		if [ $# -lt 2 ]; then
			echo 'Please specify a package-key'
			echo
			printUsage
		else
			if [ "$1" = 'package' ]; then
				shift
				ACTION='generatePackage'
				ARGUMENTS="--package-key=$1"
			fi
			if [ "$1" = 'controller' ]; then
				shift
				ACTION='generateController'
				ARGUMENTS="--package-key=$1"
				if [ $# -gt 1 ]; then
					shift
					ARGUMENTS="$ARGUMENTS --controller-name=$1"
				fi
			fi
			if [ "$1" = 'model' ]; then
				shift
				ACTION='generateModel'
				ARGUMENTS="--package-key=$1"
				if [ $# -gt 1 ]; then
					shift
					ARGUMENTS="$ARGUMENTS --model-name=$1"
					while [ $# -ge 1 ]; do
						shift
						ARGUMENTS="$ARGUMENTS $1"
					done
				fi
			fi
			if [ "$1" = 'repository' ]; then
				shift
				ACTION='generateRepository'
				ARGUMENTS="--package-key=$1"
				if [ $# -gt 1 ]; then
					shift
					ARGUMENTS="$ARGUMENTS --model-name=$1"
					while [ $# -ge 1 ]; do
						shift
						ARGUMENTS="$ARGUMENTS $1"
					done
				fi
			fi
		fi
		;;

	*)
		PACKAGE=''
		CONTROLLER=''
		ACTION=''
		ARGUMENTS=''
		;;

	esac
	shift
done



if [ "$PACKAGE" = '' -o "$CONTROLLER" = '' -o "$ACTION" = '' ]; then
	printUsage
fi

if [ "xtrue" == "x${FLOW3_DEBUG}" ]; then
    echo "FLOW3_CONTEXT     $FLOW3_CONTEXT"
    echo "FLOW3_ROOTPATH    $FLOW3_ROOTPATH"
    echo "FLOW3_WEBPATH     $FLOW3_WEBPATH"
    echo "PHP               $PHP"
    echo "PACKAGE           $PACKAGE"
    echo "SUBPACKAGES       $SUBPACKAGES"
    echo "CONTROLLER        $CONTROLLER"
    echo "ACTION            $ACTION"
    echo "ARGUMENTS         $ARGUMENTS"
    echo "COMMAND           FLOW3_CONTEXT=$FLOW3_CONTEXT FLOW3_ROOTPATH=$FLOW3_ROOTPATH FLOW3_WEBPATH=$FLOW3_WEBPATH $PHP "${FLOW3_ROOTPATH}/${BOOTSTRAP}" $PACKAGE $SUBPACKAGES $CONTROLLER $ACTION $ARGUMENTS"
    echo
    echo
fi

FLOW3_CONTEXT=$FLOW3_CONTEXT FLOW3_ROOTPATH=$FLOW3_ROOTPATH FLOW3_WEBPATH=$FLOW3_WEBPATH $PHP "${FLOW3_ROOTPATH}/${BOOTSTRAP}" $PACKAGE $SUBPACKAGES $CONTROLLER $ACTION $ARGUMENTS
